import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author HP
 */
public class CustomerOrders extends javax.swing.JFrame {

    String odate, cdate, string_t_id, string_t_id1, get_id, get_name, order_date, deadline, str_order_id, extra_des, imagePath;
    int t_id1, t_id, i, order, order_id, custom_id, tailor_id;
    float fees, height, waist, shoulder, arm, chest, thighs, wrist, neck;

    /**
     * Creates new form CustomerOrders
     */
    public CustomerOrders() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        lbl_img.setVisible(false);
        jLabel18.setVisible(false);
        jButton2.setVisible(false);
        jButton4.setVisible(false);
        lbl_img.setVisible(false);
        jLabel18.setVisible(false);
        jTextField13.setVisible(false);

    }

    private JPanel getPanel(String name, String email, String cont) {
        JPanel panel = new JPanel(new GridLayout(0, 1, 5, 5));
        JLabel nameLabel = new JLabel("Name : " + name);
        JLabel emailLabel = new JLabel("Email : " + email);
        JLabel contactLabel = new JLabel("Contact : " + cont);
        panel.add(nameLabel);
        panel.add(emailLabel);
        panel.add(contactLabel);

        return panel;
    }
    private JPanel catalog_not_chosen() {
        JPanel panel = new JPanel(new GridLayout(0, 1, 5, 5));
        JLabel nameLabel = new JLabel("Catalog reference was not chosen for this order");
        panel.add(nameLabel);

        return panel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Display_Orders = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        lbl_img = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField13 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setUndecorated(true);

        jPanel1.setLayout(null);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(790, 30, 67, 31);

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Your customer ID:");
        jLabel3.setOpaque(true);
        jPanel1.add(jLabel3);
        jLabel3.setBounds(270, 70, 180, 30);

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(0, 0, 0));
        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setBorder(null);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(450, 70, 180, 30);

        jTable_Display_Orders.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTable_Display_Orders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "OrderID", "CustomerId", "TailorId", "Order_date", "Deadline", "Completed", "Emergency"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_Display_Orders.setGridColor(new java.awt.Color(102, 102, 102));
        jTable_Display_Orders.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable_Display_OrdersMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Display_Orders);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 150, 860, 140);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tailordbconnect/rsz_1back_small.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 660, 77, 40);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tailordbconnect/logout-md.jpg"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4);
        jLabel4.setBounds(750, 660, 110, 40);

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Your Orders");
        jLabel5.setOpaque(true);
        jPanel1.add(jLabel5);
        jLabel5.setBounds(310, 20, 270, 40);

        jLabel16.setBackground(new java.awt.Color(0, 0, 0));
        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("OrderID:");
        jLabel16.setOpaque(true);
        jPanel1.add(jLabel16);
        jLabel16.setBounds(40, 300, 80, 20);

        jTextField11.setEditable(false);
        jTextField11.setBackground(new java.awt.Color(0, 0, 0));
        jTextField11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField11.setForeground(new java.awt.Color(255, 255, 255));
        jTextField11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jTextField11);
        jTextField11.setBounds(120, 300, 219, 23);

        jLabel15.setBackground(new java.awt.Color(0, 0, 0));
        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("TailorID:");
        jLabel15.setOpaque(true);
        jPanel1.add(jLabel15);
        jLabel15.setBounds(40, 330, 80, 20);

        jTextField12.setEditable(false);
        jTextField12.setBackground(new java.awt.Color(0, 0, 0));
        jTextField12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField12.setForeground(new java.awt.Color(255, 255, 255));
        jTextField12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jTextField12);
        jTextField12.setBounds(120, 330, 219, 23);

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Height:");
        jLabel6.setOpaque(true);
        jPanel1.add(jLabel6);
        jLabel6.setBounds(40, 420, 80, 20);

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(0, 0, 0));
        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(120, 420, 219, 23);

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Shoulder:");
        jLabel7.setOpaque(true);
        jPanel1.add(jLabel7);
        jLabel7.setBounds(40, 450, 80, 20);

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(0, 0, 0));
        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(255, 255, 255));
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(120, 450, 219, 23);

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Neck:");
        jLabel8.setOpaque(true);
        jPanel1.add(jLabel8);
        jLabel8.setBounds(40, 600, 80, 20);

        jTextField4.setEditable(false);
        jTextField4.setBackground(new java.awt.Color(0, 0, 0));
        jTextField4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(255, 255, 255));
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setToolTipText("");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField4);
        jTextField4.setBounds(120, 600, 217, 23);

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Waist:");
        jLabel9.setOpaque(true);
        jPanel1.add(jLabel9);
        jLabel9.setBounds(40, 630, 80, 20);

        jTextField5.setEditable(false);
        jTextField5.setBackground(new java.awt.Color(0, 0, 0));
        jTextField5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(255, 255, 255));
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jTextField5);
        jTextField5.setBounds(120, 630, 217, 23);

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Chest:");
        jLabel10.setOpaque(true);
        jPanel1.add(jLabel10);
        jLabel10.setBounds(40, 570, 80, 20);

        jTextField6.setEditable(false);
        jTextField6.setBackground(new java.awt.Color(0, 0, 0));
        jTextField6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(255, 255, 255));
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jTextField6);
        jTextField6.setBounds(120, 570, 217, 23);

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Thighs:");
        jLabel11.setOpaque(true);
        jPanel1.add(jLabel11);
        jLabel11.setBounds(40, 540, 80, 20);

        jTextField7.setEditable(false);
        jTextField7.setBackground(new java.awt.Color(0, 0, 0));
        jTextField7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(255, 255, 255));
        jTextField7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jTextField7);
        jTextField7.setBounds(120, 540, 217, 23);

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Arm:");
        jLabel12.setOpaque(true);
        jPanel1.add(jLabel12);
        jLabel12.setBounds(40, 510, 80, 20);

        jTextField8.setEditable(false);
        jTextField8.setBackground(new java.awt.Color(0, 0, 0));
        jTextField8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField8.setForeground(new java.awt.Color(255, 255, 255));
        jTextField8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jTextField8);
        jTextField8.setBounds(120, 510, 217, 23);

        jLabel13.setBackground(new java.awt.Color(0, 0, 0));
        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Wrist:");
        jLabel13.setOpaque(true);
        jPanel1.add(jLabel13);
        jLabel13.setBounds(40, 480, 80, 20);

        jTextField9.setEditable(false);
        jTextField9.setBackground(new java.awt.Color(0, 0, 0));
        jTextField9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField9.setForeground(new java.awt.Color(255, 255, 255));
        jTextField9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jTextField9);
        jTextField9.setBounds(120, 480, 217, 23);

        jLabel14.setBackground(new java.awt.Color(0, 0, 0));
        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Fees:");
        jLabel14.setOpaque(true);
        jPanel1.add(jLabel14);
        jLabel14.setBounds(40, 390, 80, 20);

        jLabel17.setBackground(new java.awt.Color(0, 0, 0));
        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Extra Description:");
        jLabel17.setOpaque(true);
        jPanel1.add(jLabel17);
        jLabel17.setBounds(470, 300, 160, 20);

        jLabel18.setBackground(new java.awt.Color(0, 0, 0));
        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Image of fabric");
        jLabel18.setOpaque(true);
        jPanel1.add(jLabel18);
        jLabel18.setBounds(470, 500, 120, 30);

        jTextField10.setEditable(false);
        jTextField10.setBackground(new java.awt.Color(0, 0, 0));
        jTextField10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField10.setForeground(new java.awt.Color(255, 255, 255));
        jTextField10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jTextField10);
        jTextField10.setBounds(120, 390, 217, 23);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("Tailor Info");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(340, 330, 100, 25);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(0, 0, 0));
        jTextArea1.setColumns(40);
        jTextArea1.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 14)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setRows(10);
        jTextArea1.setTabSize(10);
        jScrollPane2.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(470, 320, 270, 100);

        lbl_img.setBackground(new java.awt.Color(255, 255, 255));
        lbl_img.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_img.setOpaque(true);
        jPanel1.add(lbl_img);
        lbl_img.setBounds(470, 530, 140, 120);

        jLabel19.setBackground(new java.awt.Color(0, 0, 0));
        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Search by:");
        jLabel19.setOpaque(true);
        jPanel1.add(jLabel19);
        jLabel19.setBounds(170, 110, 160, 30);

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox1.setMaximumRowCount(10);
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Full list", "OrderID", "TailorID", "Not Completed", "Emergency", "Party Dress", "Casual Dress" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(330, 110, 150, 30);

        jTextField13.setBackground(new java.awt.Color(0, 0, 0));
        jTextField13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField13.setForeground(new java.awt.Color(255, 255, 255));
        jTextField13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jTextField13);
        jTextField13.setBounds(490, 110, 160, 30);

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(650, 110, 130, 30);

        jLabel20.setBackground(new java.awt.Color(0, 0, 0));
        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("CatalogID");
        jLabel20.setOpaque(true);
        jPanel1.add(jLabel20);
        jLabel20.setBounds(40, 360, 80, 20);

        jTextField14.setEditable(false);
        jTextField14.setBackground(new java.awt.Color(0, 0, 0));
        jTextField14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField14.setForeground(new java.awt.Color(255, 255, 255));
        jTextField14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jTextField14);
        jTextField14.setBounds(120, 360, 219, 23);

        jLabel21.setBackground(new java.awt.Color(0, 0, 0));
        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Dress Name");
        jLabel21.setOpaque(true);
        jPanel1.add(jLabel21);
        jLabel21.setBounds(470, 440, 120, 20);

        jLabel22.setBackground(new java.awt.Color(0, 0, 0));
        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Party or Casual");
        jLabel22.setOpaque(true);
        jPanel1.add(jLabel22);
        jLabel22.setBounds(470, 470, 120, 20);

        jTextField15.setEditable(false);
        jTextField15.setBackground(new java.awt.Color(0, 0, 0));
        jTextField15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField15.setForeground(new java.awt.Color(255, 255, 255));
        jTextField15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jTextField15);
        jTextField15.setBounds(590, 440, 217, 23);

        jTextField16.setEditable(false);
        jTextField16.setBackground(new java.awt.Color(0, 0, 0));
        jTextField16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField16.setForeground(new java.awt.Color(255, 255, 255));
        jTextField16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jTextField16);
        jTextField16.setBounds(590, 470, 217, 23);

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton4.setText("Show");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(340, 360, 100, 25);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tailordbconnect/buttons-sewing-wallpaper-49686-51364-hd-wallpapers.jpg"))); // NOI18N
        jLabel1.setToolTipText("");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, -90, 900, 810);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 890, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 815, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        dispose();
        CustomerPanel tp = new CustomerPanel();
        get_id = jTextField1.getText();
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection connection = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=TailorDBproject;selectMethod=cursor", "sa", "123456");
            Statement statement = connection.createStatement();
            ResultSet resultSet = statement.executeQuery("SELECT UserName FROM Customer WHERE CustomerId = " + get_id + "");
            if (resultSet.next()) {
                get_name = resultSet.getString("UserName");
                tp.jTextField2.setText(get_name);
                tp.jTextField1.setText(get_id);
                tp.setVisible(true);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        dispose();
        new TailorDBsigninjFrame().setVisible(true);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection connection = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=TailorDBproject;selectMethod=cursor", "sa", "123456");
            Statement statement = connection.createStatement();
            ResultSet result = statement.executeQuery("SELECT * FROM Tailor WHERE TailorID = " + Integer.parseInt(jTextField12.getText()) + "");
            while (result.next()) {
                String name = result.getString("TailorName");
                String email = result.getString("TailorEmail");
                String cont1 = "+880" + String.valueOf(result.getInt("TailorContact"));
                getPanel(name, email, cont1);
                JOptionPane.showMessageDialog(null, getPanel(name, email, cont1), "Tailor Info: ", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable_Display_OrdersMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_Display_OrdersMousePressed
        jButton4.setVisible(true);
        DefaultTableModel model = (DefaultTableModel) jTable_Display_Orders.getModel();
        i = jTable_Display_Orders.getSelectedRow();

        order = (int) model.getValueAt(i, 0);
        jButton2.setVisible(true);
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection connection = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=TailorDBproject;selectMethod=cursor", "sa", "123456");
            Statement statement = connection.createStatement();
            ResultSet result = statement.executeQuery("SELECT * FROM Orders WHERE [OrderID]=" + order + "");
            while (result.next()) {
                jTextField11.setText(Integer.toString(result.getInt("OrderID")));
                jTextField12.setText(Integer.toString(result.getInt("TailorId")));
                jTextField14.setText(Integer.toString(result.getInt("CatalogId")));
                jTextField15.setText(result.getString("DressType"));
                jTextField16.setText(result.getString("Party_Casual"));
                jTextField2.setText(String.valueOf(result.getFloat("Height")));
                jTextField4.setText(String.valueOf(result.getFloat("Neck")));
                jTextField5.setText(String.valueOf(result.getFloat("Waist")));
                jTextField3.setText(String.valueOf(result.getFloat("Shoulder")));
                jTextField6.setText(String.valueOf(result.getFloat("Chest")));
                jTextField7.setText(String.valueOf(result.getFloat("Thighs")));
                jTextField8.setText(String.valueOf(result.getFloat("Arm")));
                jTextField9.setText(String.valueOf(result.getFloat("Wrist")));
                jTextField10.setText(String.valueOf(result.getFloat("fee")));
                jTextArea1.setText(result.getString("ExtraDescribe"));
                lbl_img.setVisible(true);
                jLabel18.setVisible(true);
                ImageIcon imageIcon = new ImageIcon(new ImageIcon(result.getString("ImagePath")).getImage().getScaledInstance(lbl_img.getWidth(), lbl_img.getHeight(), Image.SCALE_SMOOTH));
                lbl_img.setIcon(imageIcon);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jTable_Display_OrdersMousePressed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        if (jComboBox1.getSelectedItem().equals("OrderID")) {
            jTextField13.setVisible(true);
        } else if (jComboBox1.getSelectedItem().equals("TailorID")) {
            jTextField13.setVisible(true);
        } else if (jComboBox1.getSelectedItem().equals("Emergency")) {
            jTextField13.setVisible(false);
        } else if (jComboBox1.getSelectedItem().equals("Not Completed")) {
            jTextField13.setVisible(false);
        } else if (jComboBox1.getSelectedItem().equals("Full list")) {
            jTextField13.setVisible(false);
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable_Display_Orders.getModel();
        int rowCount = model.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--) {
            model.removeRow(i);
        }
        ArrayList<Orders> orderList = new ArrayList();
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection connection = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=TailorDBproject;selectMethod=cursor", "sa", "123456");
            Statement statement = connection.createStatement();
            if ((jComboBox1.getSelectedItem().toString()).equals("OrderID")) {
                jTextField13.setVisible(true);
                ResultSet resultSet = statement.executeQuery("SELECT * FROM Orders WHERE OrderID = " + Integer.parseInt(jTextField13.getText()) + " and CustomerId = " + jTextField1.getText() + "");
                while (resultSet.next()) {
                    Orders orders;
                    orders = new Orders(resultSet.getInt("OrderID"), resultSet.getInt("CustomerId"), resultSet.getInt("TailorId"), resultSet.getDate("OrderDate").toString(), resultSet.getDate("CompletingDate").toString(), resultSet.getString("Completed"), resultSet.getString("Emergency_make"), resultSet.getBytes("Image"));
                    orderList.add(orders);
                    ArrayList<Orders> list = orderList;

                    Object[] row = new Object[7];
                    for (int i = 0; i < list.size(); i++) {
                        row[0] = list.get(i).get_order_id();
                        row[1] = list.get(i).get_customer_id();
                        row[2] = list.get(i).get_tailor_id();
                        row[3] = list.get(i).get_order_date();
                        row[4] = list.get(i).get_complete_date();
                        row[5] = list.get(i).completed();
                        row[6] = list.get(i).emergency();
                        model.addRow(row);

                    }
                    orderList.clear();
                }
            } else if ((jComboBox1.getSelectedItem().toString()).equals("TailorID")) {
                 jTextField13.setVisible(true);
                ResultSet resultSet = statement.executeQuery("SELECT * FROM Orders WHERE CustomerId = " + Integer.parseInt(jTextField1.getText()) + " and TailorId = " + jTextField13.getText() + "");
                while (resultSet.next()) {
                    Orders orders;
                    orders = new Orders(resultSet.getInt("OrderID"), resultSet.getInt("CustomerId"), resultSet.getInt("TailorId"), resultSet.getDate("OrderDate").toString(), resultSet.getDate("CompletingDate").toString(), resultSet.getString("Completed"), resultSet.getString("Emergency_make"), resultSet.getBytes("Image"));
                    orderList.add(orders);
                    ArrayList<Orders> list = orderList;
                    Object[] row = new Object[7];
                    for (int i = 0; i < list.size(); i++) {
                        row[0] = list.get(i).get_order_id();
                        row[1] = list.get(i).get_customer_id();
                        row[2] = list.get(i).get_tailor_id();
                        row[3] = list.get(i).get_order_date();
                        row[4] = list.get(i).get_complete_date();
                        row[5] = list.get(i).completed();
                        row[6] = list.get(i).emergency();
                        model.addRow(row);

                    }
                    orderList.clear();

                }
            } else if ((jComboBox1.getSelectedItem().toString()).equals("Emergency")) {
                 jTextField13.setVisible(false);
                ResultSet resultSet = statement.executeQuery("SELECT * FROM Orders WHERE Emergency_make = 'YES' and CustomerId = " + jTextField1.getText() + "");
                while (resultSet.next()) {
                    Orders orders;
                    orders = new Orders(resultSet.getInt("OrderID"), resultSet.getInt("CustomerId"), resultSet.getInt("TailorId"), resultSet.getDate("OrderDate").toString(), resultSet.getDate("CompletingDate").toString(), resultSet.getString("Completed"), resultSet.getString("Emergency_make"), resultSet.getBytes("Image"));
                    orderList.add(orders);
                    ArrayList<Orders> list = orderList;

                    Object[] row = new Object[7];
                    for (int i = 0; i < list.size(); i++) {
                        row[0] = list.get(i).get_order_id();
                        row[1] = list.get(i).get_customer_id();
                        row[2] = list.get(i).get_tailor_id();
                        row[3] = list.get(i).get_order_date();
                        row[4] = list.get(i).get_complete_date();
                        row[5] = list.get(i).completed();
                        row[6] = list.get(i).emergency();
                        model.addRow(row);

                    }
                    orderList.clear();
                }

            } else if ((jComboBox1.getSelectedItem().toString()).equals("Not Completed")) {
                 jTextField13.setVisible(false);
                ResultSet resultSet = statement.executeQuery("SELECT * FROM Orders WHERE Completed = 'NO' and CustomerId = " + jTextField1.getText() + "");
                while (resultSet.next()) {
                    Orders orders;
                    orders = new Orders(resultSet.getInt("OrderID"), resultSet.getInt("CustomerId"), resultSet.getInt("TailorId"), resultSet.getDate("OrderDate").toString(), resultSet.getDate("CompletingDate").toString(), resultSet.getString("Completed"), resultSet.getString("Emergency_make"), resultSet.getBytes("Image"));
                    orderList.add(orders);
                    ArrayList<Orders> list = orderList;

                    Object[] row = new Object[7];
                    for (int i = 0; i < list.size(); i++) {
                        row[0] = list.get(i).get_order_id();
                        row[1] = list.get(i).get_customer_id();
                        row[2] = list.get(i).get_tailor_id();
                        row[3] = list.get(i).get_order_date();
                        row[4] = list.get(i).get_complete_date();
                        row[5] = list.get(i).completed();
                        row[6] = list.get(i).emergency();
                        model.addRow(row);

                    }
                    orderList.clear();

                }
            } 
            else if ((jComboBox1.getSelectedItem().toString()).equals("Party Dress")) {
                 jTextField13.setVisible(false);
                ResultSet resultSet = statement.executeQuery("SELECT * FROM Orders WHERE Party_Casual = 'Party' and CustomerId = " + jTextField1.getText() + "");
                while (resultSet.next()) {
                    Orders orders;
                    orders = new Orders(resultSet.getInt("OrderID"), resultSet.getInt("CustomerId"), resultSet.getInt("TailorId"), resultSet.getDate("OrderDate").toString(), resultSet.getDate("CompletingDate").toString(), resultSet.getString("Completed"), resultSet.getString("Emergency_make"), resultSet.getBytes("Image"));
                    orderList.add(orders);
                    ArrayList<Orders> list = orderList;

                    Object[] row = new Object[7];
                    for (int i = 0; i < list.size(); i++) {
                        row[0] = list.get(i).get_order_id();
                        row[1] = list.get(i).get_customer_id();
                        row[2] = list.get(i).get_tailor_id();
                        row[3] = list.get(i).get_order_date();
                        row[4] = list.get(i).get_complete_date();
                        row[5] = list.get(i).completed();
                        row[6] = list.get(i).emergency();
                        model.addRow(row);

                    }
                    orderList.clear();

                }
            } 
            else if ((jComboBox1.getSelectedItem().toString()).equals("Casual Dress")) {
                 jTextField13.setVisible(false);
                ResultSet resultSet = statement.executeQuery("SELECT * FROM Orders WHERE Party_Casual = 'Casual' and CustomerId = " + jTextField1.getText() + "");
                while (resultSet.next()) {
                    Orders orders;
                    orders = new Orders(resultSet.getInt("OrderID"), resultSet.getInt("CustomerId"), resultSet.getInt("TailorId"), resultSet.getDate("OrderDate").toString(), resultSet.getDate("CompletingDate").toString(), resultSet.getString("Completed"), resultSet.getString("Emergency_make"), resultSet.getBytes("Image"));
                    orderList.add(orders);
                    ArrayList<Orders> list = orderList;

                    Object[] row = new Object[7];
                    for (int i = 0; i < list.size(); i++) {
                        row[0] = list.get(i).get_order_id();
                        row[1] = list.get(i).get_customer_id();
                        row[2] = list.get(i).get_tailor_id();
                        row[3] = list.get(i).get_order_date();
                        row[4] = list.get(i).get_complete_date();
                        row[5] = list.get(i).completed();
                        row[6] = list.get(i).emergency();
                        model.addRow(row);

                    }
                    orderList.clear();

                }
            }
            else if ((jComboBox1.getSelectedItem().toString()).equals("Full list")) {
                 jTextField13.setVisible(false);
                ResultSet resultSet = statement.executeQuery("SELECT * FROM Orders WHERE CustomerId =" + Integer.parseInt(jTextField1.getText()) + "");
                while (resultSet.next()) {
                    Orders orders;
                    orders = new Orders(resultSet.getInt("OrderID"), resultSet.getInt("CustomerId"), resultSet.getInt("TailorId"), resultSet.getDate("OrderDate").toString(), resultSet.getDate("CompletingDate").toString(), resultSet.getString("Completed"), resultSet.getString("Emergency_make"), resultSet.getBytes("Image"));
                    orderList.add(orders);
                    ArrayList<Orders> list = orderList;

                    Object[] row = new Object[7];
                    for (int i = 0; i < list.size(); i++) {
                        row[0] = list.get(i).get_order_id();
                        row[1] = list.get(i).get_customer_id();
                        row[2] = list.get(i).get_tailor_id();
                        row[3] = list.get(i).get_order_date();
                        row[4] = list.get(i).get_complete_date();
                        row[5] = list.get(i).completed();
                        row[6] = list.get(i).emergency();
                        model.addRow(row);

                    }
                    orderList.clear();
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if((jTextField14.getText()).equals("1")){
            catalog_not_chosen();
            JOptionPane.showMessageDialog(null, catalog_not_chosen(), "", JOptionPane.INFORMATION_MESSAGE);
           
        }
        else{
        Show_catalog_customer c = new Show_catalog_customer();
        c.jTextField3.setText(jTextField1.getText());
        c.jTextField5.setText(jTextField11.getText());
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection connection = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=TailorDBproject;selectMethod=cursor", "sa", "123456");
            Statement statement = connection.createStatement();
            ResultSet result = statement.executeQuery("SELECT * FROM Catalog WHERE [catalogID]=" + Integer.parseInt(jTextField14.getText()) + "");
            while (result.next()) {
                c.jTextField1.setText(result.getString("DressName"));
                c.jTextField4.setText(Integer.toString(result.getInt("catalogID")));
                ImageIcon imageIcon = new ImageIcon(new ImageIcon(result.getString("Imagepath")).getImage().getScaledInstance(c.lbl_img.getWidth(), c.lbl_img.getHeight(), Image.SCALE_SMOOTH));
                c.lbl_img.setIcon(imageIcon);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        dispose();
        c.setVisible(true);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerOrders().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    public javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    public javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    public javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable jTable_Display_Orders;
    public javax.swing.JTextArea jTextArea1;
    public javax.swing.JTextField jTextField1;
    public javax.swing.JTextField jTextField10;
    public javax.swing.JTextField jTextField11;
    public javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    public javax.swing.JTextField jTextField14;
    public javax.swing.JTextField jTextField15;
    public javax.swing.JTextField jTextField16;
    public javax.swing.JTextField jTextField2;
    public javax.swing.JTextField jTextField3;
    public javax.swing.JTextField jTextField4;
    public javax.swing.JTextField jTextField5;
    public javax.swing.JTextField jTextField6;
    public javax.swing.JTextField jTextField7;
    public javax.swing.JTextField jTextField8;
    public javax.swing.JTextField jTextField9;
    public javax.swing.JLabel lbl_img;
    // End of variables declaration//GEN-END:variables
}
