import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HP
 */
public class TailorDBsigninjFrame extends javax.swing.JFrame {
    public String s1,tableName,name;
    public int s,flag = 0;
    /**
     * Creates new form TailorDBsigninjFrame
     */
    public TailorDBsigninjFrame() {

        initComponents();

        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        txtemail.setBackground(new java.awt.Color(0, 0, 0, 1));
        txtpass.setBackground(new java.awt.Color(0, 0, 0, 1));
        jPanel1.setBackground(new Color(0, 0, 0, 0));
        //signinas_setString.setBackground(new java.awt.Color(0,0,0,1));
        signinas_combo.setModel(new DefaultComboBoxModel<>(new String[]{
            "--- Sign in as ---", "Tailor", "Customer"
        }));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        signin_btn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtpass = new javax.swing.JPasswordField();
        signinas_combo = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setUndecorated(true);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jLabel2.setText("Email:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(310, 60, 120, 30);

        txtemail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtemail.setBorder(null);
        txtemail.setDisabledTextColor(new java.awt.Color(0, 51, 51));
        jPanel1.add(txtemail);
        txtemail.setBounds(310, 110, 270, 30);

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jLabel3.setText("Passsword:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(310, 170, 140, 30);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(310, 140, 270, 10);
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(310, 250, 280, 10);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tailordbconnect/Makower-FQ-bundle-sign-in1.jpg"))); // NOI18N
        jLabel4.setText("Sign-in");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel4.setOpaque(true);
        jPanel1.add(jLabel4);
        jLabel4.setBounds(-480, 0, 750, 510);

        signin_btn.setBackground(new java.awt.Color(255, 255, 255));
        signin_btn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        signin_btn.setText("Sign-in");
        signin_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signin_btnActionPerformed(evt);
            }
        });
        jPanel1.add(signin_btn);
        signin_btn.setBounds(300, 430, 120, 40);

        jButton2.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(720, 20, 63, 29);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Don't have an account?");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(430, 455, 150, 10);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 153));
        jLabel6.setText("<html> <body> <u>Sign - up</u> </body> </html>");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6);
        jLabel6.setBounds(580, 450, 70, 17);

        txtpass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtpass.setBorder(null);
        txtpass.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jPanel1.add(txtpass);
        txtpass.setBounds(310, 220, 280, 30);

        signinas_combo.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        signinas_combo.setBorder(null);
        signinas_combo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                signinas_comboItemStateChanged(evt);
            }
        });
        jPanel1.add(signinas_combo);
        signinas_combo.setBounds(410, 300, 170, 30);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jLabel7.setText("Sign-in as:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(310, 304, 100, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tailordbconnect/lux-velvet-6031-baby-blue-fabric-2-zoom-big.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(270, 0, 540, 520);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 804, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        dispose();
        new TailorDBsignupjFrame().setVisible(true);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void signin_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signin_btnActionPerformed


        if (!(txtemail.getText().length() <= 0)) {
           if((txtemail.getText().contains("@gmail.com") || txtemail.getText().contains("@yahoo.com") || txtemail.getText().contains("@outlook.com"))){
            String email = txtemail.getText();
            String password = txtpass.getText();
            try {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                Connection connection = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=TailorDBproject;selectMethod=cursor", "sa", "123456");
                Statement statement = connection.createStatement();
           
                if (signinas_combo.getSelectedItem().toString().equals("Customer")) {
                   
                    ResultSet resultSet = statement.executeQuery("SELECT * FROM Customer WHERE [Email]='" + email + "' and [Pass]='" + password + "'");
                    if (resultSet.next()) {
                        CustomerPanel cp = new CustomerPanel();
                        cp.jTextField1.setText(Integer.toString(resultSet.getInt("CustomerID")));
                        cp.jTextField2.setText(resultSet.getString("UserName"));
                        dispose();
                        cp.setVisible(true);

                    } else {
                        JOptionPane.showMessageDialog(null, "Email and password not correct");
                    }
                } else if (signinas_combo.getSelectedItem().toString().equals("Tailor")) {
                  
                    ResultSet resultSet = statement.executeQuery("SELECT * FROM Tailor WHERE [TailorEmail]='" + email + "' and [TailorPass]='" + password + "'");
                    if (resultSet.next()) {
                        TailorPanel tp = new TailorPanel();
                       
                        tp.jTextField1.setText(Integer.toString(resultSet.getInt("TailorID")));
                        tp.jTextField2.setText(resultSet.getString("TailorName"));
                        dispose();
                        tp.setVisible(true);
                       
                    } else {
                        JOptionPane.showMessageDialog(null, "Email and password not correct");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Sign in as?", "Sign in", JOptionPane.QUESTION_MESSAGE);
                }

            } catch (Exception e) {
                e.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Invalid Email Address");
        }
    }
    }//GEN-LAST:event_signin_btnActionPerformed

    private void signinas_comboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_signinas_comboItemStateChanged

    }//GEN-LAST:event_signinas_comboItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TailorDBsigninjFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TailorDBsigninjFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TailorDBsigninjFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TailorDBsigninjFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TailorDBsigninjFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton signin_btn;
    private javax.swing.JComboBox<String> signinas_combo;
    private javax.swing.JTextField txtemail;
    private javax.swing.JPasswordField txtpass;
    // End of variables declaration//GEN-END:variables
}
